version: '2'
services:
    demo_jhipster-app:
        image: demo_jhipster
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://demo_jhipster-mysql:3306/demo_jhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demo_jhipster-mysql:
        extends:
            file: mysql.yml
            service: demo_jhipster-mysql
